// ============ TASK LIBRARY ============
// Edit freely. Each task: [name, roughly-every-N-days, days it can happen (null = any; 0=Sun ... 6=Sat), minutes it takes, energy 1-3]
// Add a new category by adding a new key. Renaming a task changes its id, so it restarts its history.
// Things you hide in the app stay hidden even after you update this file.
window.TASK_LIBRARY = {
  Body: [
    ["Stretch 10 min", 1, null, 10, 1], ["Swim", 3, [1, 3, 5], 60, 3], ["Strength session", 3, [2, 4, 6], 60, 3],
    ["Walk without phone", 2, null, 30, 1], ["Mobility / foam roll", 4, null, 15, 1], ["Long walk (1h+)", 7, [0, 6], 75, 2],
    ["Run 5k", 4, null, 35, 3], ["Easy run", 3, null, 30, 2], ["Long run", 14, [0, 6], 70, 3], ["Intervals / hill sprints", 10, null, 40, 3],
    ["Cycle somewhere", 7, null, 60, 2], ["Yoga video", 4, null, 25, 2], ["Pilates / core", 4, null, 20, 2],
    ["Cold shower finish", 2, null, 2, 2], ["Weigh in", 7, [1], 1, 1], ["Log workouts for the week", 7, [0], 10, 1],
    ["Book physio / massage", 60, null, 5, 1], ["Dentist check-up booked?", 180, null, 5, 1], ["Eye test booked?", 365, null, 5, 1],
    ["Take vitamins", 1, null, 1, 1], ["10k steps", 1, null, 60, 2], ["Sauna / steam", 14, null, 45, 1],
    ["Push-up / pull-up mini set", 2, null, 5, 2], ["Check in on any niggles", 7, null, 5, 1], ["Deload / rest week check", 42, null, 5, 1],
    ["Plan next training block", 30, [0], 30, 2], ["Test a lift / time a distance", 30, null, 45, 3], ["Posture check — sit up", 1, null, 1, 1],
    ["Walk to the next stop instead", 3, null, 15, 1], ["Take the stairs all day", 2, null, 1, 1], ["Hip / glute activation", 3, null, 10, 1],
    ["Neck & shoulder release", 3, null, 8, 1], ["Grip / forearm work", 7, null, 10, 1], ["Balance / single-leg work", 5, null, 10, 1],
    ["Swim technique drills", 10, [1, 3, 5], 45, 2], ["Try a class (spin, boxing, climbing)", 30, null, 60, 3], ["Sunlight in the first hour", 1, null, 10, 1],
  ],
  Sleep: [
    ["In bed by 11", 1, null, 1, 1], ["No screens after 10pm", 1, null, 1, 1], ["Wake at the same time", 1, null, 1, 1],
    ["No caffeine after 2pm", 1, null, 1, 1], ["Change pillowcase", 7, null, 3, 1], ["Air the bedroom", 3, null, 2, 1],
    ["Phone charges outside the bedroom", 1, null, 1, 1], ["Wind-down routine (20 min)", 1, null, 20, 1], ["No alcohol tonight", 2, null, 1, 1],
    ["Blackout / curtains sorted", 90, null, 10, 1], ["Rotate / flip mattress", 180, null, 15, 2], ["Wash duvet / pillows", 120, null, 20, 2],
    ["Review sleep data for the week", 7, [0], 5, 1], ["Nap if needed (20 min max)", 5, null, 20, 1], ["Read in bed instead of scroll", 2, null, 20, 1],
  ],
  Food: [
    ["Cook a proper dinner", 2, null, 45, 2], ["Batch cook for the week", 7, [0], 90, 3], ["Big food shop", 7, [0, 6], 60, 2],
    ["Top-up shop", 3, null, 20, 1], ["Plan meals for the week", 7, [0, 6], 15, 1], ["Try a new recipe", 10, null, 60, 2],
    ["Clear out fridge", 14, null, 15, 1], ["Eat 5 veg today", 1, null, 1, 1], ["Drink 2L water", 1, null, 1, 1],
    ["No takeaway this week", 7, null, 1, 1], ["Make lunch instead of buying", 2, [1, 2, 3, 4, 5], 15, 1],
    ["Bake something", 21, [0, 6], 90, 2], ["Check cupboard dates", 60, null, 15, 1], ["Sharpen kitchen knives", 90, null, 15, 1],
    ["Proper breakfast", 1, null, 15, 1], ["Prep veg / snacks for the week", 7, [0], 30, 2], ["Make a soup / stew", 10, null, 60, 2],
    ["Fish for dinner", 7, null, 30, 2], ["Meat-free day", 3, null, 1, 1], ["Protein with every meal", 1, null, 1, 1],
    ["Eat without a screen", 1, null, 20, 1], ["Cook for the freezer", 14, [0, 6], 90, 3], ["Defrost & use something from the freezer", 7, null, 5, 1],
    ["Restock spices / staples", 60, null, 20, 1], ["Try a new café / lunch spot", 14, [1, 2, 3, 4, 5], 60, 1], ["Learn one knife skill / technique", 30, null, 20, 2],
    ["Go to a market", 21, [0, 6], 60, 2], ["Bread from scratch", 30, [0, 6], 120, 3], ["Fruit in the bowl this week", 7, null, 5, 1],
    ["Clean the coffee machine / cafetière", 14, null, 10, 1], ["Write down a recipe you nailed", 21, null, 10, 1],
  ],
  Home: [
    ["Tidy desk", 2, null, 5, 1], ["Make the bed", 1, null, 2, 1], ["Wash up / dishwasher", 1, null, 10, 1],
    ["Wipe kitchen surfaces", 2, null, 5, 1], ["Hoover living room", 7, null, 15, 2], ["Hoover bedroom", 10, null, 10, 2],
    ["Hoover hallway / stairs", 10, null, 10, 2], ["Mop kitchen floor", 14, null, 15, 2], ["Mop bathroom floor", 14, null, 10, 2],
    ["Clean bathroom", 10, null, 25, 2], ["Clean the loo", 5, null, 5, 1], ["Clean the sink & taps", 5, null, 5, 1],
    ["Change bed sheets", 10, [0, 6], 15, 2], ["Wash towels", 7, null, 10, 1], ["Laundry", 4, null, 15, 1],
    ["Put laundry away", 4, null, 10, 1], ["Iron shirts", 7, [0], 30, 2], ["Take bins out", 7, null, 5, 1],
    ["Recycling out", 14, null, 5, 1], ["Empty all small bins", 7, null, 5, 1], ["Water plants", 5, null, 5, 1], ["Feed / repot plants", 60, null, 20, 2],
    ["Descale kettle", 60, null, 10, 1], ["Clean microwave", 21, null, 10, 1], ["Clean oven", 90, null, 45, 3], ["Clean hob", 7, null, 10, 1],
    ["Clean extractor fan / filter", 90, null, 20, 2], ["Clean fridge inside", 45, null, 25, 2], ["Defrost freezer", 180, null, 60, 2],
    ["Wipe skirting boards", 60, null, 30, 2], ["Clean windows", 90, null, 45, 2], ["Clean window sills", 30, null, 10, 1],
    ["Dust shelves", 14, null, 15, 1], ["Dust lampshades / light fittings", 60, null, 15, 1], ["Wipe door handles & switches", 21, null, 10, 1],
    ["Declutter one drawer", 14, null, 15, 1], ["Declutter one shelf / cupboard", 21, null, 20, 1], ["Sort the 'stuff' pile", 10, null, 20, 1],
    ["Clean shower head / limescale", 45, null, 15, 2], ["Wash shower curtain / screen", 30, null, 15, 2], ["Clean grout", 120, null, 45, 3],
    ["Wash the car", 30, [0, 6], 40, 2], ["Check smoke alarm", 90, null, 2, 1], ["Bleed radiators", 180, null, 20, 2], ["Boiler / heating check", 365, null, 15, 1],
    ["Wash bath mat", 14, null, 5, 1], ["Hoover under sofa", 60, null, 15, 2], ["Hoover / wash sofa cushions", 90, null, 30, 2],
    ["Clear email / post pile by the door", 7, null, 10, 1], ["Wash reusable bags", 60, null, 5, 1], ["Clean the bin itself", 30, null, 10, 2],
    ["Wash the dishwasher filter", 30, null, 10, 1], ["Run washing machine cleaning cycle", 60, null, 5, 1], ["Wipe the washing machine seal", 30, null, 5, 1],
    ["Clean the toaster crumbs", 30, null, 5, 1], ["Clean under the sink", 90, null, 20, 2], ["Sort the medicine drawer", 120, null, 15, 1],
    ["Replace toothbrush head", 90, null, 2, 1], ["Clean the hoover itself", 60, null, 15, 2], ["Tidy cables", 60, null, 20, 1],
    ["Change lightbulb / batteries that need it", 30, null, 10, 1], ["Wipe mirrors", 14, null, 5, 1], ["Wash curtains / blinds", 180, null, 30, 2],
    ["Deep clean one room", 30, [0, 6], 90, 3], ["Fix the thing that's been annoying you", 14, null, 30, 2], ["Hang / frame that picture", 60, null, 30, 2],
    ["Fresh flowers / plant for the flat", 21, null, 15, 1], ["Air the whole flat", 3, null, 5, 1], ["Sort the recycling properly", 14, null, 10, 1],
    ["Restock loo roll / cleaning stuff", 21, null, 10, 1], ["Check for damp / leaks", 60, null, 10, 1], ["Sort keys / spares", 180, null, 10, 1],
  ],
  Garden: [
    ["Water outdoor plants", 3, null, 10, 1], ["Weed a bed / pots", 14, [0, 6], 30, 2], ["Mow / trim", 14, [0, 6], 30, 2],
    ["Sweep balcony / patio", 14, null, 15, 1], ["Deadhead / prune", 14, null, 15, 1], ["Feed plants", 21, null, 10, 1],
    ["Plant something new", 45, [0, 6], 45, 2], ["Sort outdoor furniture / cushions", 60, null, 20, 1], ["Clean gutters / drains", 180, null, 45, 3],
    ["Fill the bird feeder", 7, null, 5, 1], ["Clear leaves", 14, null, 20, 2], ["Herbs on the windowsill", 60, null, 20, 1],
  ],
  Admin: [
    ["Inbox to zero", 3, null, 20, 2], ["Check bank & card statements", 7, null, 10, 1], ["Pay / review bills", 30, null, 15, 1],
    ["Weekly review", 7, [0, 1], 30, 2], ["Plan tomorrow", 1, null, 5, 1], ["Plan the week", 7, [0], 20, 2], ["Back up laptop", 30, null, 5, 1],
    ["Back up phone photos", 30, null, 10, 1], ["Review subscriptions", 90, null, 15, 1], ["Update passwords / 2FA check", 120, null, 20, 2],
    ["File receipts", 14, null, 10, 1], ["Check pension / ISA", 60, null, 15, 2], ["Renew anything expiring?", 30, null, 10, 1],
    ["Return / cancel anything pending", 14, null, 10, 1], ["Clear phone notifications & apps", 30, null, 10, 1],
    ["Update budget", 7, [0, 1], 15, 2], ["Check calendar for next 2 weeks", 7, [0], 5, 1], ["Sort out a nagging admin thing", 5, null, 20, 2],
    ["Read one T&C / letter properly", 14, null, 15, 1], ["Tax / HMRC check-in", 90, null, 20, 2], ["Check insurance renewals", 180, null, 15, 1],
    ["Passport expiry check", 365, null, 2, 1], ["Driving licence / address up to date", 365, null, 5, 1], ["Electoral roll / council tax check", 365, null, 10, 1],
    ["Clear downloads folder", 14, null, 10, 1], ["Empty desktop / tidy files", 30, null, 20, 1], ["Unsubscribe from 5 emails", 14, null, 10, 1],
    ["Reply to anything older than 3 days", 3, null, 15, 1], ["Sort physical post / paperwork", 14, null, 15, 1], ["Shred old documents", 90, null, 20, 1],
    ["Check loyalty points / vouchers", 60, null, 10, 1], ["Book the thing you keep meaning to book", 7, null, 10, 1], ["Update emergency contacts / ICE", 365, null, 5, 1],
    ["Meter readings", 30, null, 5, 1], ["Compare energy / broadband / phone deal", 180, null, 30, 2], ["Check parking / travel cards / season tickets", 60, null, 10, 1],
    ["Digital declutter: photos", 30, null, 20, 1], ["Digital declutter: apps", 60, null, 15, 1], ["Digital declutter: bookmarks / notes", 60, null, 20, 1],
    ["Warranty / receipts folder", 90, null, 10, 1], ["Write a will / check beneficiaries", 365, null, 30, 2], ["Charity giving check", 90, null, 10, 1],
  ],
  Money: [
    ["Move money to savings", 30, null, 5, 1], ["Check for a better rate", 90, null, 20, 2], ["Review last month's spending", 30, [0, 1], 20, 2],
    ["Sell something you don't use", 30, null, 30, 2], ["Check credit report", 120, null, 10, 1], ["Cancel one thing you don't use", 60, null, 10, 1],
    ["Set / review a savings goal", 90, null, 15, 2], ["Look at investments (don't fiddle)", 30, null, 15, 1], ["No-spend day", 3, null, 1, 1],
    ["Pay off card in full", 30, null, 5, 1], ["Top up ISA before deadline", 365, null, 10, 1], ["Review pension contributions", 180, null, 20, 2],
    ["Update net worth tracker", 30, [0, 1], 15, 1], ["Check for cashback / refunds owed", 30, null, 10, 1], ["Read one personal finance thing", 14, null, 20, 1],
    ["Round up spare change", 30, null, 5, 1], ["Plan big purchases for the year", 90, null, 30, 2], ["Check the emergency fund is intact", 60, null, 5, 1],
  ],
  Mind: [
    ["Read 20 pages", 1, null, 20, 1], ["Journal", 2, null, 10, 1], ["Meditate 10 min", 2, null, 10, 1],
    ["Gratitude — 3 things", 1, null, 3, 1], ["No phone first 30 min", 1, null, 1, 1], ["Screen-free evening", 7, null, 120, 1],
    ["Long-form article", 4, null, 30, 1], ["Podcast episode on a walk", 4, null, 45, 1], ["Write a page of whatever", 7, null, 30, 2],
    ["Review goals for the quarter", 30, [0], 30, 2], ["Write down what's bugging you", 5, null, 10, 1], ["Do nothing for 15 min", 3, null, 15, 1],
    ["Learn something new (10 min)", 3, null, 10, 1], ["Museum / gallery", 45, [0, 6], 120, 2], ["Finish a book", 21, null, 90, 2],
    ["Chess puzzle / brain game", 3, null, 10, 1], ["Breathing exercise (5 min)", 2, null, 5, 1], ["Sit outside with a coffee", 3, null, 20, 1],
    ["Write 3 things that went well", 1, null, 3, 1], ["Say no to something", 7, null, 1, 1], ["Tidy your mind: brain dump", 5, null, 10, 1],
    ["Reread old journal entries", 30, null, 20, 1], ["Write down one thing you learned today", 1, null, 2, 1], ["Start the day without news", 1, null, 1, 1],
    ["Limit social media to 30 min", 1, null, 1, 1], ["Listen to a full album, no phone", 7, null, 45, 1], ["Plan a treat / reward", 7, null, 5, 1],
    ["Reflect on the month", 30, [0], 30, 2], ["Revisit your 'why' for the year", 60, null, 20, 2], ["Digital sabbath (half day)", 14, [0, 6], 240, 1],
  ],
  People: [
    ["Call home", 7, [0], 30, 1], ["Message a friend you've not seen", 5, null, 5, 1], ["Plan something social", 10, null, 10, 2],
    ["Round of golf with Louis", 21, [0, 6], 240, 3], ["Send a thank-you / follow-up", 7, null, 10, 1], ["Reply to the message you've left", 2, null, 5, 1],
    ["Coffee with someone", 7, null, 60, 2], ["Check birthdays this month", 30, [0, 1], 5, 1], ["Send a card / present", 30, null, 20, 1],
    ["Visit family", 45, [0, 6], 240, 2], ["Host / cook for people", 30, [0, 6], 180, 3], ["Voice note a mate", 7, null, 5, 1],
    ["Say yes to an invite", 14, null, 1, 1], ["Grandparents / older relative call", 14, null, 20, 1], ["Catch-up with an ex-colleague", 30, [1, 2, 3, 4, 5], 60, 2],
    ["Dinner with friends", 14, [4, 5, 6], 150, 2], ["Pub / drinks", 10, [4, 5, 6], 120, 2], ["Organise the group trip / dinner", 60, null, 30, 2],
    ["Ask someone how they're actually doing", 5, null, 10, 1], ["Introduce two people who should meet", 30, null, 10, 1], ["Write a proper letter / long message", 60, null, 30, 2],
    ["Call a friend abroad", 30, null, 45, 1], ["Family WhatsApp — actually reply", 3, null, 5, 1], ["Do a favour for someone", 14, null, 30, 2],
    ["Plan a visit to see someone far away", 90, null, 20, 2], ["Remember an anniversary / occasion", 30, null, 10, 1], ["Weekend with mates", 60, [5, 6], 480, 3],
    ["Reconnect with someone you've lost touch with", 45, null, 10, 2], ["Be somewhere on time for someone", 7, null, 1, 1], ["Cook for / with a housemate or partner", 14, null, 60, 2],
  ],
  Study: [
    ["CFA: 1 reading", 2, null, 60, 3], ["CFA: question bank set", 2, null, 30, 2], ["CFA: flashcard review", 1, null, 15, 1],
    ["CFA: mock exam section", 14, [0, 6], 120, 3], ["CFA: review weak topics", 7, null, 45, 2], ["CFA: update study tracker", 7, [0], 10, 1],
    ["CFA: ethics reading", 7, null, 45, 2], ["CFA: formula sheet review", 5, null, 20, 1], ["CFA: full mock", 30, [0, 6], 270, 3],
    ["CFA: check exam logistics / booking", 60, null, 10, 1], ["CFA: redo wrong answers", 4, null, 30, 2],
    ["Felix Pro modelling session", 4, null, 60, 3], ["Rebuild a model from scratch", 21, null, 120, 3], ["Read one broker note properly", 3, null, 30, 2],
    ["Read a results release + call", 7, null, 45, 2], ["Practise Excel shortcuts 10 min", 3, null, 10, 1], ["Write up what you learned this week", 7, [0], 20, 2],
    ["Accounting concept deep-dive", 5, null, 30, 2], ["Watch a finance lecture", 7, null, 45, 2], ["Tableau refresher", 30, null, 45, 2],
    ["Python / automation practice", 5, null, 45, 2], ["Build a DCF for a company you like", 30, null, 120, 3], ["Read an annual report cover to cover", 30, null, 120, 2],
    ["Valuation multiples practice", 10, null, 30, 2], ["Read one FT / Economist piece properly", 3, null, 20, 1], ["Summarise a paper / report in 5 bullets", 7, null, 30, 2],
    ["Teach a concept back to yourself out loud", 7, null, 15, 2], ["Update your 'things I know' doc", 14, null, 20, 1], ["Learn one new Excel function", 7, null, 15, 1],
    ["SQL practice", 10, null, 30, 2], ["Statistics refresher", 14, null, 30, 2], ["Read a chapter of a finance / econ book", 3, null, 30, 1],
  ],
  "Job search": [
    ["Scan job boards", 2, null, 15, 1], ["Reach out to one contact", 3, [1, 2, 3, 4], 15, 2], ["Tailor CV for a live role", 7, [1, 2, 3, 4, 5], 60, 3],
    ["Interview prep session", 5, null, 45, 3], ["Update LinkedIn", 30, null, 20, 2], ["Follow up on an application", 4, [1, 2, 3, 4, 5], 10, 1],
    ["Research one target company", 4, null, 30, 2], ["Recruiter check-in", 7, [1, 2, 3, 4], 15, 2], ["Practise 'tell me about yourself'", 7, null, 15, 2],
    ["Update application tracker", 3, null, 10, 1], ["Write a cover letter", 7, [1, 2, 3, 4, 5], 45, 3], ["Ask for a reference / intro", 14, null, 10, 2],
    ["Read sector news for interviews", 2, null, 20, 1], ["Rehearse a case / model test", 10, null, 60, 3], ["Post something on LinkedIn", 14, [1, 2, 3, 4], 20, 2],
    ["Prep 3 stories (STAR)", 14, null, 45, 2], ["Prep questions to ask them", 7, null, 15, 1], ["Mock interview with a friend", 21, null, 60, 3],
    ["Refresh the target company list", 14, null, 30, 2], ["Check salary benchmarks", 60, null, 20, 1], ["Review your CV for typos, fresh eyes", 30, null, 20, 1],
    ["Message a headhunter", 10, [1, 2, 3, 4], 10, 2], ["Comment on 3 LinkedIn posts", 5, [1, 2, 3, 4, 5], 10, 1], ["Attend an event / talk", 30, null, 120, 2],
    ["Write a thank-you after an interview", 7, null, 10, 1], ["Debrief after an interview (what to improve)", 7, null, 20, 2], ["Portfolio / work samples up to date", 30, null, 45, 2],
    ["Check job alerts are set right", 30, null, 10, 1], ["Read a company's latest results before interview", 7, null, 45, 2], ["Practise a brainteaser / market sizing", 10, null, 20, 2],
  ],
  Career: [
    ["Write up a project you're proud of", 30, null, 45, 2], ["Update the 'brag file'", 14, null, 10, 1], ["Read something in your field", 3, null, 30, 1],
    ["Think about where you want to be in 3 years", 90, null, 30, 2], ["Ask someone for feedback", 30, null, 15, 2], ["Mentor / help someone junior", 30, null, 30, 2],
    ["Find a mentor / sounding board", 90, null, 20, 2], ["Learn a tool everyone in your field uses", 30, null, 60, 2], ["Publish / share a piece of thinking", 30, null, 90, 3],
    ["Keep the contacts spreadsheet current", 30, null, 20, 1], ["Read a book about your industry", 60, null, 120, 2], ["Give a talk / present something", 90, null, 60, 3],
  ],
  Golf: [
    ["Range session", 7, null, 60, 2], ["Putting drill at home", 3, null, 15, 1], ["Book lesson with Dan", 45, null, 5, 1],
    ["Short game practice", 10, null, 45, 2], ["9 holes", 14, null, 120, 3], ["Watch swing video back", 7, null, 10, 1],
    ["Clean clubs", 30, null, 15, 1], ["Book a tee time", 14, null, 5, 1], ["Chipping in the garden", 5, null, 15, 1],
    ["Stretch for golf", 3, null, 10, 1], ["18 holes", 21, [0, 6], 270, 3], ["Bunker practice", 21, null, 30, 2],
    ["Work on one thing from the last lesson", 5, null, 20, 2], ["Log scores / stats", 14, null, 10, 1], ["Regrip / check kit", 180, null, 30, 2],
    ["Play a new course", 60, [0, 6], 300, 3], ["Watch a tournament / learn from the pros", 30, null, 60, 1], ["Check handicap", 30, null, 5, 1],
    ["Restock balls / tees / glove", 60, null, 15, 1], ["Play with someone better than you", 30, null, 240, 3],
  ],
  Fun: [
    ["Watch a film properly", 7, null, 120, 1], ["Game for an hour, guilt-free", 5, null, 60, 1], ["Go somewhere new in London", 14, [0, 6], 180, 2],
    ["Live music / comedy / sport", 30, null, 180, 2], ["Cook something ambitious", 21, [0, 6], 120, 3],
    ["Day trip", 45, [0, 6], 360, 3], ["Photos — sort and pick favourites", 30, null, 30, 1], ["Plan a holiday / weekend away", 60, null, 45, 2],
    ["Try a new pub / café", 14, null, 90, 1], ["Read the paper cover to cover", 7, [0, 6], 60, 1], ["Listen to a new album", 5, null, 45, 1],
    ["Board game / cards night", 30, null, 150, 2], ["Cinema", 21, null, 150, 1], ["Theatre / show", 60, null, 180, 2],
    ["Walk somewhere green", 7, null, 90, 2], ["Swim outdoors / lido", 30, [0, 6], 90, 2], ["Watch the match", 7, null, 120, 1],
    ["Pick up the guitar / instrument", 4, null, 20, 1], ["Draw / doodle for 15 min", 7, null, 15, 1], ["Watch a documentary", 10, null, 90, 1],
    ["Long lazy breakfast out", 14, [0, 6], 90, 1], ["Explore a new neighbourhood", 21, [0, 6], 150, 2], ["Go to a talk / lecture", 30, null, 120, 2],
    ["Buy tickets for something 2 months out", 30, null, 15, 1], ["Rewatch a favourite film", 30, null, 120, 1], ["Try a new sport / activity", 60, null, 120, 3],
    ["Start a new TV series", 30, null, 60, 1], ["Finish the TV series", 30, null, 120, 1], ["Sports on the radio while cooking", 7, null, 45, 1],
  ],
  Creative: [
    ["Work on the sweepstakes app", 4, null, 90, 3], ["Work on the Today app", 7, null, 60, 3], ["Write 500 words of anything", 7, null, 45, 2],
    ["Learn one new song / piece", 30, null, 60, 2], ["Take 10 proper photos", 14, null, 45, 1], ["Sketch an idea for a project", 14, null, 20, 1],
    ["Write down 10 ideas", 7, null, 10, 1], ["Ship something small", 14, null, 60, 3], ["Fix a bug that's been bugging you", 7, null, 45, 2],
    ["Read about a technology you don't understand", 10, null, 30, 2], ["Write a blog post / newsletter", 30, null, 90, 3], ["Make something with your hands", 30, null, 120, 2],
    ["Revisit an old project", 60, null, 45, 2], ["Contribute to something open-source", 60, null, 90, 3], ["Learn a new keyboard shortcut / tool", 7, null, 10, 1],
  ],
  Travel: [
    ["Book the flights you've been circling", 30, null, 30, 2], ["Research one destination", 21, null, 30, 1], ["Check passport / visas / ETA for next trip", 60, null, 10, 1],
    ["Make a packing list template", 180, null, 20, 1], ["Book accommodation", 45, null, 30, 2], ["Plan a weekend away", 60, null, 45, 2],
    ["Travel insurance sorted", 180, null, 15, 1], ["Sort the trip itinerary", 60, null, 45, 2], ["Print / save tickets offline", 30, null, 5, 1],
    ["Learn 10 words of the local language", 30, null, 20, 1], ["Empty and sort the travel bag", 60, null, 15, 1], ["Check phone roaming / eSIM", 60, null, 10, 1],
    ["Do the UK trip you've been meaning to", 90, [5, 6], 480, 3], ["Write up / photo-book the last trip", 60, null, 60, 2],
  ],
  Style: [
    ["Haircut", 28, null, 45, 1], ["Shave / trim", 3, null, 10, 1], ["Nails", 10, null, 10, 1], ["Skincare, morning and night", 1, null, 3, 1],
    ["Sun cream if it's sunny", 1, null, 1, 1], ["Iron / steam tomorrow's outfit", 3, null, 10, 1], ["Buy the thing you actually need", 30, null, 30, 2],
    ["Try on what doesn't fit — donate", 90, null, 30, 1], ["Sort socks / pants — bin the dead ones", 90, null, 15, 1], ["Polish / clean shoes", 21, null, 15, 1],
    ["Restock toiletries", 30, null, 10, 1], ["Get a suit / jacket cleaned or pressed", 90, null, 10, 1], ["Book a barber ahead", 21, null, 3, 1],
    ["Moisturise", 1, null, 1, 1], ["Floss", 1, null, 2, 1], ["Whiten / mouthwash", 2, null, 1, 1],
  ],
  Kit: [
    ["Charge everything", 3, null, 5, 1], ["Clean laptop screen & keyboard", 21, null, 10, 1], ["Clean phone", 7, null, 3, 1],
    ["Polish shoes", 30, null, 20, 1], ["Wash trainers", 45, null, 15, 1], ["Sort out wardrobe", 60, null, 45, 2],
    ["Drop off charity bag", 60, null, 20, 1], ["Replace worn-out thing", 30, null, 20, 1], ["Wash coat / jacket", 90, null, 10, 1],
    ["Check bike / tyres", 30, null, 15, 1], ["Sew on that button", 30, null, 15, 1], ["Update software everywhere", 30, null, 15, 1],
    ["Clean headphones / earbuds", 14, null, 5, 1], ["Wash gym bag / kit bag", 30, null, 10, 1], ["Wash water bottle properly", 3, null, 3, 1],
    ["Clean glasses / sunglasses", 7, null, 2, 1], ["Sort the cable / charger drawer", 90, null, 20, 1], ["Check first aid kit", 180, null, 10, 1],
    ["Test the umbrella / raincoat still works", 180, null, 5, 1], ["Wax / reproof boots or jacket", 180, null, 30, 2], ["Wash swim kit & goggles", 3, null, 5, 1],
    ["Restock batteries / bulbs", 90, null, 10, 1], ["Sort the tool box", 180, null, 20, 1], ["Sharpen / oil anything that needs it", 90, null, 15, 1],
  ],
  Car: [
    ["Check tyre pressures", 30, null, 10, 1], ["Check oil & screenwash", 30, null, 10, 1], ["Fill up before it's empty", 7, null, 10, 1],
    ["Hoover inside the car", 30, null, 20, 2], ["Clear the boot / glovebox", 60, null, 15, 1], ["MOT booked?", 365, null, 5, 1],
    ["Service booked?", 365, null, 5, 1], ["Tax / insurance renewal check", 180, null, 10, 1], ["Check lights & wipers", 60, null, 5, 1],
    ["Wash the car", 30, [0, 6], 40, 2], ["Check tread / tyre wear", 90, null, 5, 1], ["Sort parking permit", 365, null, 15, 1],
  ],
  Community: [
    ["Volunteer / help out", 30, null, 120, 2], ["Give blood", 90, null, 60, 2], ["Donate to something", 60, null, 10, 1],
    ["Pick up litter on a walk", 30, null, 20, 1], ["Say hello to a neighbour", 14, null, 5, 1], ["Support a local shop / café", 7, null, 20, 1],
    ["Sign up for a charity run / event", 180, null, 15, 1], ["Take stuff to the charity shop", 60, null, 30, 1], ["Vote / check voter registration", 365, null, 10, 1],
    ["Leave a good review for someone who deserved it", 30, null, 10, 1], ["Offer to help a friend with something", 30, null, 60, 2],
  ],
  Seasonal: [
    ["Swap wardrobe for the season", 180, [0, 6], 60, 2], ["Sort winter coat / boots", 365, null, 30, 1], ["Christmas presents: list", 365, null, 30, 1],
    ["Christmas presents: buy", 365, null, 120, 2], ["Book Christmas / New Year travel", 365, null, 30, 2], ["Plan summer holidays", 365, null, 60, 2],
    ["Bike out of storage / serviced", 365, null, 30, 2], ["BBQ / garden ready for summer", 365, [0, 6], 60, 2], ["Check heating before winter", 365, null, 15, 1],
    ["Spring clean weekend", 365, [0, 6], 240, 3], ["Birthday plans for the month", 30, [0, 1], 10, 1], ["New year: review the year", 365, null, 60, 2],
    ["Mid-year: check goals", 365, null, 45, 2], ["Renew golf membership / sub", 365, null, 10, 1], ["Book the annual thing (festival / trip)", 365, null, 20, 1],
  ],
  London: [
    ["Walk a bit of the Thames Path", 30, [0, 6], 120, 2], ["Exhibition that's on right now", 45, null, 120, 2], ["Try a new market", 30, [0, 6], 90, 1],
    ["Climb a viewpoint (Primrose Hill, Greenwich…)", 60, [0, 6], 120, 2], ["Get on a Boris bike somewhere", 30, null, 60, 2], ["Try a food spot you've saved", 14, null, 90, 1],
    ["Free thing: Tate / BM / NPG", 60, null, 120, 1], ["Cheap theatre / day seats", 60, null, 180, 2], ["A park you've never been to", 45, [0, 6], 120, 2],
    ["Take the river bus somewhere", 90, null, 90, 1], ["Book something at the Barbican / Southbank", 60, null, 15, 1], ["Sunday pub lunch out of town", 60, [0], 180, 2],
  ],
};

// Tasks you start with on first run. Format: "Category:Task name". Anything else waits in the Library.
window.STARTER_TASKS = [
  "Body:Stretch 10 min", "Body:Swim", "Body:Strength session", "Body:Walk without phone", "Home:Tidy desk", "Home:Hoover living room",
  "Home:Change bed sheets", "Home:Clean bathroom", "Home:Descale kettle", "Home:Water plants", "Food:Big food shop", "Food:Batch cook for the week",
  "Admin:Inbox to zero", "Admin:Check bank & card statements", "Admin:Weekly review", "Admin:Plan tomorrow", "Mind:Read 20 pages", "Mind:Journal",
  "People:Call home", "People:Message a friend you've not seen", "People:Round of golf with Louis", "Study:CFA: 1 reading", "Study:CFA: question bank set",
  "Study:CFA: flashcard review", "Study:Felix Pro modelling session", "Job search:Scan job boards", "Job search:Reach out to one contact",
  "Job search:Tailor CV for a live role", "Job search:Interview prep session", "Golf:Range session", "Golf:Putting drill at home",
];
